name: CI
on:
  push:
    branches: ["master"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: echo "npm -v && echo "node -v"
      - run: npm ci
      - run: npm lint
